name: dadi
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - jupyterlab_widgets
  - ipywidgets
  - voila
  - numpy
  - scipy
  - dadi
  - snakemake
  - pip
  - pip:
    - nlopt
    - matplotlib
    - jupyterlab-hide-code
